blog/urls.py
from django.urls import path
from .views import *
app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/comment/', BlogCommentView.as_view(), name='blog_comment')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blogs')),
    path('', include('pages.urls', namespace='pages')),
    path('shop/', include('shop.urls', namespace='shop')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutUsView, ContactView

app_name = "pages"

urlpatterns = [
    path('', HomePageView.as_view(), name='home', ),
    path('about/', AboutUsView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
]

shop/urls.py
from django.urls import path
from .views import ShopView, ProductDetailView, ShopCardView

app_name = 'shops'

urlpatterns = [
    path('', ShopView.as_view(), name='shop'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('<int:pk>/shopcard/', ShopCardView.as_view(), name='shopcard'),
]

blog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class AuthorModel(models.Model):
    first_name = models.CharField(max_length=100, verbose_name=_('first name'))
    last_name = models.CharField(max_length=100, verbose_name=_('last name'))
    avatar = models.ImageField(upload_to='author-avatars/', verbose_name=_('avatar'))

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'author'
        verbose_name_plural = 'authors'


class BlogTagModel(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('title'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class BlogPostModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    description = models.TextField(verbose_name=_('description'))
    main_image = models.ImageField(upload_to='blog-post-img/', verbose_name=_('main image'))
    banner = models.ImageField(upload_to='blog-post-img/', verbose_name=_('banner'))
    author = models.ForeignKey(AuthorModel, on_delete=models.RESTRICT, related_name='posts', verbose_name=_('author'))
    tags = models.ManyToManyField(BlogTagModel, related_name='posts', verbose_name=_('tags'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    
    def __str__(self):
        return '{} ...'.format(self.title[:100])

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'


class CommentModel(models.Model):
    post = models.ForeignKey(BlogPostModel,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name=_('post'),
                             )
    name = models.CharField(max_length=64, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    phone = models.CharField(max_length=13, verbose_name=_('phone'))
    comment = models.TextField(verbose_name=_('comment'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.name

shop/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class ColorModel(models.Model):
    code = models.CharField(max_length=7, verbose_name=_("code"))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = _('color')
        verbose_name_plural = _('colors')


class SizeModel(models.Model):
    name = models.CharField(max_length=5, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('size')
        verbose_name_plural = _('sizes')


class BrandModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('brand')
        verbose_name_plural = _('brands')


class TagModel(models.Model):
    name = models.CharField(max_length=54, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('tag')
        verbose_name_plural = _('tags')


class CategoryModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')


class ProductModel(models.Model):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    image = models.ImageField(upload_to='products', verbose_name=_('image'))
    price = models.FloatField(verbose_name=_('price'))
    discount = models.PositiveIntegerField(default=0, verbose_name=_('discount'))
    short_description = models.TextField(verbose_name=_('short description'))
    long_description = models.TextField(verbose_name=_('long description'))
    category = models.ForeignKey(
        CategoryModel,
        on_delete=models.PROTECT,
        related_name='products',
        verbose_name=_('category')
    )
    brand = models.ForeignKey(
        BrandModel,
        on_delete=models.PROTECT,
        related_name='products',
        verbose_name=_('brand'),
        null=True,
        blank=True
    )
    tag = models.ManyToManyField(
        TagModel,
        related_name='products',
        verbose_name=_('tag')
    )
    color = models.ManyToManyField(
        ColorModel,
        related_name='products',
        verbose_name=_('color'),
        null=True,
        blank=True,
    )
    size = models.ManyToManyField(
        SizeModel,
        related_name='products',
        verbose_name=_('size'),
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created at'))

    def get_price(self):
        if self.discount == 0:
            return self.price
        return (100 - self.discount) / 100 * self.price

    def is_new(self):
        return (timezone.now() - self.created_at).days <= 3

    def is_discount(self):
        return self.discount != 0

    def get_related(self):
        return ProductModel.objects.filter(category__name=self.category).exclude(pk=self.pk)[:4]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')

blog/forms.py
from pyexpat import model

from django.forms.models import ModelForm
from .models import CommentModel

class CommentModelForm(ModelForm):
    class Meta:
        model = CommentModel
        exclude =['post', 'created_at']

shop/forms.py
from django import forms
from .models import ColorModel, ProductModel


class ColorModelForm(forms.ModelForm):
    code = forms.CharField(max_length=7, widget=forms.TextInput(attrs={'type': 'color'}),)

    class Meta:
        model = ColorModel
        fields = '__all__'

class ProductModelModelForm(forms.ModelForm):
    color = forms.CharField(max_length=7, widget=forms.TextInput(attrs={'type': 'color'}),)

    class Meta:
        model = ProductModel
        fields = ['color']

blog/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView

from .forms import CommentModelForm
from .models import BlogPostModel, CommentModel
from .forms import CommentModelForm



class BlogListView(ListView):
    template_name = 'main/blog.html'
    queryset = BlogPostModel.objects.order_by('-pk')
    model = BlogPostModel
    context_object_name = 'posts'

    def get_queryset(self, *args, **kwargs):
        qs = BlogPostModel.objects.order_by('-pk')
        tag = self.request.GET.get('tag')
        if tag:
            return qs.filter(tags__title=tag)
        return qs

class BlogDetailView(DetailView):
    model = BlogPostModel
    template_name = 'main/blog-details.html'
    context_object_name = 'post'


class BlogCommentView(CreateView):
    form_class = CommentModelForm

    def form_valid(self, form):
        form.instance.post = get_object_or_404(BlogPostModel, pk=self.kwargs.get('pk'))
        return super(BlogCommentView, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_detail', kwargs={'pk': self.kwargs.get('pk')})

shop/views.py
import color as color
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from .models import *


class ShopView(ListView):
    model = ProductModel
    paginate_by = 6
    template_name = 'main/shop.html'

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super(ShopView, self, *args, **kwargs).get_context_data()
        context['categories'] = CategoryModel.objects.all()
        context['brands'] = BrandModel.objects.all()
        context['tags'] = TagModel.objects.all()
        context['colors'] = ColorModel.objects.all()
        context['sizes'] = SizeModel.objects.all()
        return context

    def get_queryset(self):
        qs = ProductModel.objects.all()
        q = self.request.GET.get('q')
        if q:
            qs = qs.filter(name__icontains=q)
            return qs

        cat = self.request.GET.get('cat')
        if cat:
            qs = qs.filter(category_id=cat)

        brand = self.request.GET.get('brand')
        if brand:
            qs = qs.filter(brand_id=brand)

        tag = self.request.GET.get('tag')
        if tag:
            qs = qs.filter(tag__name=tag)

        size = self.request.GET.get('size')
        if size:
            qs = qs.filter(size_id=size)

        color = self.request.GET.get('color')
        if color:
            qs = qs.filter(color_id=color)

        return qs


class ProductDetailView(DetailView):
    model = ProductModel
    template_name = 'main/shop-details.html'

class ShopCardView(TemplateView):
    template_name = 'main/shopping-cart.html'

templates/main/blog-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Blog Details Hero Begin -->
    <section class="blog-hero spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="blog__hero__text">
                        <h2>{{ post.title }}</h2>
                        <ul>
                            <li>By {{ post.author }}</li>
                            <li>{{ post.created_at|date:'F d, Y' }}</li>
                            <a href="#comments">
                                <li>{{ post.comments.all.count }} Comments</li>
                            </a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ post.banner.url }}" alt="">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__share">
                            <span>share</span>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                                <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="blog__details__text">
                            <p>Hydroderm is the highly desired anti-aging cream on the block. This serum restricts the
                                occurrence of early aging sings on the skin and keeps the skin younger, tighter and
                                healthier. It reduces the wrinkles and loosening of skin. This cream nourishes the skin
                                and brings back the glow that had lost in the run of hectic years.</p>
                            <p>The most essential ingredient that makes hydroderm so effective is Vyo-Serum, which is a
                                product of natural selected proteins. This concentrate works actively in bringing about
                                the natural youthful glow of the skin. It tightens the skin along with its moisturizing
                                effect on the skin. The other important ingredient, making hydroderm so effective is
                                “marine collagen” which along with Vyo-Serum helps revitalize the skin.</p>
                        </div>

                        <div class="blog__details__text">
                            <p>{{ post.description }}</p>
                        </div>
                        <div class="blog__details__option">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__author">
                                        <div class="blog__details__author__pic">
                                            <img src="{{ post.author.avatar.url }}" alt="{{ blog.title }}">
                                        </div>
                                        <div class="blog__details__author__text">
                                            <h5>{{ post.author }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for tag in post.tags.all %}
                                            <a href="{% url 'blog:blog_list' %}?tag={{ tag }}">#{{ tag }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if post.get_previous_by_created_at %}
                                        <a href="{% url 'blog:blog_detail' pk=post.get_previous_by_created_at.pk %}"
                                           class="blog__details__btns__item">
                                            <p><span class="arrow_left"></span> Previous Pod</p>
                                            <h5>{{ post.get_previous_by_created_at.title }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if post.get_next_by_created_at %}
                                        <a href="{% url 'blog:blog_detail' pk=post.get_next_by_created_at.pk %}"
                                           class="blog__details__btns__item blog__details__btns__item--next">
                                            <p>Next Pod <span class="arrow_right"></span></p>
                                            <h5>{{ post.get_next_by_created_at.title }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        {% if post.comments.all %}
                            <div class="blog__details__comment pt-4" id="comments">
                                <h4>All Comment</h4>
                            </div>
                        {% endif %}

                        {% for comment in post.comments.all %}
                            <div class="blog__details__quote">
                                <i class="fa fa-quote-left"></i>
                                <p>
                                    “{{ comment.comment }}”
                                </p>
                                <h6>User : _ {{ comment.name }} _</h6>
                                <div class="text-right">
                                    <p>{{ comment.created_at|timesince }} ago</p>
                                </div>
                            </div>
                        {% endfor %}

                        <div class="blog__details__comment">
                            <h4>Leave A Comment</h4>
                            <form action="{% url 'blog:blog_comment' pk=post.id %}" method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-4 col-md-4">
                                        <input name="name" type="text" placeholder="Name">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="email" type="text" placeholder="Email">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="phone" type="text" placeholder="Phone">
                                    </div>
                                    <div class="col-lg-12 text-center">
                                        <textarea name="comment" placeholder="Comment"></textarea>
                                        <button type="submit" class="site-btn">Post Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->
{% endblock %}

templates/main/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Map Begin -->
    <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2996.653982009868!2d69.2285874158241!3d41.31639047927076!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8ba287dd9341%3A0x966819d2fe0d7c38!2sSamarqand%20Darvoza!5e0!3m2!1sru!2s!4v1645015286696!5m2!1sru!2s" height="500" style="border:0;" allowfullscreen=""
                aria-hidden="false" tabindex="0"></iframe>
    </div>
    <!-- Map End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="contact__text">
                        <div class="section-title">
                            <span>Information</span>
                            <h2>Contact Us</h2>
                            <p>As you might expect of a company that began as a high-end interiors contractor, we pay
                                strict attention.</p>
                        </div>
                        <ul>
                            <li>
                                <h4>America</h4>
                                <p>195 E Parker Square Dr, Parker, CO 801 <br/>+43 982-314-0958</p>
                            </li>
                            <li>
                                <h4>France</h4>
                                <p>109 Avenue Léon, 63 Clermont-Ferrand <br/>+12 345-423-9893</p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="contact__form">
                        <form action="{% url 'pages:contact' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6">
                                    <input type="text" name="name" placeholder="Name">
                                </div>
                                <div class="col-lg-6">
                                    <input type="text" name="email" placeholder="Email">
                                </div>
                                <div class="col-lg-12">
                                    <textarea name="message" placeholder="Message"></textarea>
                                    <button type="submit" class="site-btn">Send Message</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->
{% endblock %}

templates/main/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/main/shop.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <style>
        a:hover{
            cursor: pointer;
        }
    </style>
{% endblock %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'pages:home' %}">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="shop__sidebar">
                        {% include 'layouts/shop_sidebar.html' %}
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="shop__product__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__left">
                                    <p>Showing {{ page_obj.start_index }}–{{ page_obj.end_index }}
                                        of {{ page_obj.paginator.count }} results</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__right">
                                    <p>Sort by Price:</p>
                                    <select>
                                        <option value="">- - -</option>
                                        <option value="">Low To High</option>
                                        <option value="">High To Low</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for object in object_list %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                <div class="product__item {% if object.is_discount %}sale{% endif %}">
                                    <div class="product__item__pic set-bg" data-setbg="{{ object.image.url }}">
                                        {% if object.is_discount %}
                                            <span class="label">Sale</span>
                                        {% endif %}
                                        {% if object.is_new %}
                                            <span style="background: white; color: #000;{% if object.is_discount %} margin-top: 2rem;{% endif %}"
                                                  class="label">New</span>
                                        {% endif %}
                                        <ul class="product__hover">
                                            <li><a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                                            </li>
                                            <li><a href="#"><img src="{% static 'img/icon/compare.png' %}" alt="">
                                                <span>Compare</span></a>
                                            </li>
                                            <li><a href="{% url 'shops:product_detail' pk=object.pk %}"><img
                                                    src="{% static 'img/icon/search.png' %}" alt=""></a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="product__item__text">
                                        <h6>{{ object.name }}</h6>
                                        <a href="#" class="add-cart">+ Add To Cart</a>
                                        <div class="rating">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star-o"></i>
                                        </div>
                                        <h5>
                                            ${% if object.is_discount %}
                                            {{ object.get_price }}
                                        {% else %}
                                            {{ object.price }}
                                        {% endif %}
                                        </h5>
                                        <div class="product__color__select">
                                            <label for="pc-7">
                                                <input type="radio" id="pc-7">
                                            </label>
                                            <label class="active black" for="pc-8">
                                                <input type="radio" id="pc-8">
                                            </label>
                                            <label class="grey" for="pc-9">
                                                <input type="radio" id="pc-9">
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-lg-12">

                            {% if page_obj.paginator.count > 3 %}
                                <section class="container mb-4 pb-5">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="product__pagination">
                                                {% for page in page_obj.paginator.page_range %}
                                                    <a {% if page == page_obj.number %}class="active"{% endif %}
                                                       href="?page={{ page }}">
                                                        {{ page }}
                                                    </a>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </section>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->

{% endblock %}

{% block extra_js %}
    <script>
        function getParamSearch(name, value) {
        var searchParams = new URLSearchParams(window.location.search);
        if (searchParams.has(name) && searchParams.get(name) == value) {
            searchParams.delete(name);
        } else {
            searchParams.set(name, value);
        }
        window.location.search = searchParams.toString();
    }
    </script>
{% endblock %}