blog/urls.py
from django.urls import path
from .views import *
app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/comment/', BlogCommentView.as_view(), name='blog_comment')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blogs')),
    path('', include('pages.urls', namespace='pages')),
    path('shop/', include('shop.urls', namespace='shop')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutUsView, ContactView

app_name = "pages"

urlpatterns = [
    path('', HomePageView.as_view(), name='home', ),
    path('about/', AboutUsView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
]

shop/urls.py
from django.urls import path
from .views import ShopView, ProductDetailView, ShopCardView

app_name = 'shops'

urlpatterns = [
    path('', ShopView.as_view(), name='shop'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('<int:pk>/shopcard/', ShopCardView.as_view(), name='shopcard'),
]

templates/layouts/footer.html
{% load static %}

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                        </div>
                        <p>The customer is at the heart of our unique business model, which includes design.</p>
                        <a href="#"><img src="{% static 'img/payment.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="#">Clothing Store</a></li>
                            <li><a href="#">Trending Shoes</a></li>
                            <li><a href="#">Accessories</a></li>
                            <li><a href="#">Sale</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="{% url 'pages:contact' %}">Contact Us</a></li>
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Delivary</a></li>
                            <li><a href="#">Return & Exchanges</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>NewLetter</h6>
                        <div class="footer__newslatter">
                            <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <button type="submit"><span class="icon_mail_alt"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="footer__copyright__text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Copyright ©
                            <script>
                                document.write(new Date().getFullYear());
                            </script>
                            All rights reserved | This template is made with <i class="fa fa-heart-o"
                            aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        </p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

templates/layouts/navbar.html
{% load static %}

<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            <a href="#">Sign in</a>
            <a href="#">FAQs</a>
        </div>
        <div class="offcanvas__top__hover">
            <span>Usd <i class="arrow_carrot-down"></i></span>
            <ul>
                <li>USD</li>
                <li>EUR</li>
                <li>USD</li>
            </ul>
        </div>
    </div>
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="img/icon/search.png" alt=""></a>
        <a href="#"><img src="img/icon/heart.png" alt=""></a>
        <a href="#"><img src="img/icon/cart.png" alt=""> <span>0</span></a>
        <div class="price">$0.00</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
        <p>Free shipping, 30-day return or refund guarantee.</p>
    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        <p>Free shipping, 30-day return or refund guarantee.</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            <a href="#">Sign in</a>
                            <a href="#">FAQs</a>
                        </div>
                        <div class="header__top__hover">
                            <span>Usd <i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>USD</li>
                                <li>EUR</li>
                                <li>USD</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'pages:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">

                    <ul>
                        <li class="{% if request.path == '/'%} active {% endif %}">
                            <a href="{% url 'pages:home' %}">Home</a>
                        </li>
                        <li class="{% if request.path == '/shop/'%} active {% endif %}">
                            <a href="{% url 'shops:shop' %}">Shop</a>
                        </li>
                        <li class="{% if request.path == '/blog/'%} active {% endif %}">
                            <a href="{% url 'blog:blog_list' %}">Blog</a>
                        </li>
                        <li class="{% if request.path == '/about/'%} active {% endif %}">
                            <a href="{% url 'pages:about' %}">About Us</a>
                        </li>
                        <li class="{% if request.path == '/contact/'%} active {% endif %}">
                            <a href="{% url 'pages:contact' %}">Contacts</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
                    <div class="price">$0.00</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

templates/layouts/shop_sidebar.html
<div class="shop__sidebar__search">
    <form action="{% url 'shops:shop' %}">
        <input value="{{ request.GET.q }}" name="q" type="text" placeholder="Search...">
        <button type="submit"><span class="icon_search"></span></button>
    </form>
</div>
<div class="shop__sidebar__accordion">
    <div class="accordion" id="accordionExample">
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
            </div>
            <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__categories">
                        <ul class="nice-scroll">
                            {% for category in categories %}
                                <li><a {% if request.GET.cat == category.pk|stringformat:'i' %}
                                    class="text-dark"{% endif %} onclick="getParamSearch('cat', {{ category.pk }})">{{ category }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
            </div>
            <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__brand">
                        <ul>
                            {% for b in brands %}
                                <li>
                                    <a {% if request.GET.brand == b.pk|stringformat:'i' %} class="text-dark"{% endif %}
                                            onclick="getParamSearch('brand', {{ b.pk }})">{{ b }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
            </div>
            <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__price">
                        <ul>
                            <li><a href="#">$0.00 - $50.00</a></li>
                            <li><a href="#">$50.00 - $100.00</a></li>
                            <li><a href="#">$100.00 - $150.00</a></li>
                            <li><a href="#">$150.00 - $200.00</a></li>
                            <li><a href="#">$200.00 - $250.00</a></li>
                            <li><a href="#">250.00+</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseFour">Size</a>
            </div>
            <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__size">
                        {% for size in sizes %}
                            <label>
                                <a onclick="getParamSearch('size', {{ size.pk }})">{{ size }}</a>
                            </label>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
            </div>
            <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__color">
                        {% for color in colors %}
                                <label style="background:{{ color.code }}">
                                    <a onclick="getParamSearch('color', {{ color.pk }})"></a>
                                </label>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-heading">
                <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
            </div>
            <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                <div class="card-body">
                    <div class="shop__sidebar__tags">
                        {% for tag in tags %}
                            <a
                                    {% if request.GET.tag == tag.name %} class="bg-dark text-white"{% endif %}
                                    onclick="getParamSearch('tag', {{ tag.pk }})">
                                {{ tag }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>